---
- name: "Gather installed packages"
  ansible.builtin.package_facts:
    manager: apt

- name: "Set missing packages to the install list"
  ansible.builtin.set_fact:
    packages_to_install: "{{ packages_list | difference(ansible_facts.packages.keys() | list) }}"

- name: "Install packages: {{ packages_to_install }}"
  become: "{{ activemq_install_requires_become | default(true) }}"
  ansible.builtin.apt:
    name: "{{ packages_to_install }}"
    state: present
    update_cache: true
  when: packages_to_install | default([]) | length > 0