---
- name: Playbook to deploy activemq in master/standby with shared datadir
  hosts: all
  vars:
    activemq_ha_enabled: true
    activemq_disable_hornetq_protocol: true
    activemq_installdir: "/opt/amq/apache-artemis-{{ activemq_version }}"
    activemq_dest: /var/lib/brokers
    activemq_replication_enabled: true
    activemq_shared_storage: false
    activemq_version: 2.42.0
    activemq_instance_name: "{{ ansible_hostname }}"
    ### below listed varibale should be moved to Debian.yml vars file
    activemq_sysconfig_dir: /etc/default
    activemq_java_home: /usr/lib/jvm/java-17-openjdk-amd64/
    activemq_jvm_package: openjdk-17-jre-headless
    activemq_java_opts_mem: '-Xms20G -Xmx20G'
    activemq_global_max_size: 4GB
    activemq_acceptors:
      - name: "artemis"
        scheme: tcp
        bind_address: "{{ activemq_bind_address }}"
        bind_port: 61616
        parameters:
          ssl: false
          protocols: "CORE,AMQP"
      - name: "amqp-internal"
        scheme: tcp
        bind_port: 45671
        bind_address: "{{ activemq_bind_address }}"
        parameters:
          ssl: false
          protocols: "CORE,AMQP"
      - name: "mqtt-tls"
        scheme: tcp
        bind_port: 48883
        bind_address: "{{ activemq_bind_address }}"
        parameters:
          ssl: false
          protocols: "MQTT"
          serverKeepAlive: 0
      - name: "artemis-internal"
        scheme: tcp
        bind_port: 48884
        bind_address: "{{ activemq_bind_address }}"
        parameters:
          ssl: false
          protocols: "MQTT"
    activemq_connectors:
      - name: "artemis"
        uri: "tcp://{{ activemq_bind_address }}:61616"
  roles:
   - /root/amq_artemis/amq-ubuntu/roles/activemq