---
- name: Playbook to deploy activemq in master/standby with shared datadir
  hosts: all
  vars:
    activemq_ha_enabled: true
    activemq_disable_hornetq_protocol: true
    activemq_replication_enabled: true
    activemq_shared_storage: false
    activemq_configure_firewalld: true
  roles:
   - /root/amq_artemis/amq-ubuntu/roles/activemq