---
- name: Playbook to deploy activemq in master/standby with shared datadir
  hosts: all
  vars:
    activemq_ha_enabled: true
    activemq_disable_hornetq_protocol: true
    activemq_replication_enabled: true
    activemq_shared_storage: false
    ### below listed varibale should be moved to Debian.yml vars file
    activemq_sysconfig_dir: /etc/default
    activemq_java_home: /usr/lib/jvm/java-17-openjdk-amd64/
    activemq_jvm_package: openjdk-17-jre-headless
  roles:
   - /root/amq_artemis/amq-ubuntu/roles/activemq